/* gveejay - Linux VeeJay - GVeejay GTK+-3/Glade User Interface
 *           (C) 2002-2018 Niels Elburg <nwelburg@gmail.com>
 *  with contributions by  Jerome Blanchi (2016-2018)
 *                        (Gtk3 Migration and other stuff)
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#ifndef GVRCOMMON_H
#define GVRCOMMON_H

#include <veejaycore/vims.h>

#define STATUS_LENGTH 2048
#define VEEJAY_CODENAME VERSION

#define ELAPSED_TIME 0
#define PLAY_MODE 2
#define CURRENT_ID 3
#define SAMPLE_FX 4
#define SAMPLE_START 5
#define SAMPLE_END 6
#define SAMPLE_SPEED 7
#define SAMPLE_LOOP 8
#define SAMPLE_COUNT 12
#define SAMPLE_MARKER_START   13
#define STREAM_TYPE 13
#define SAMPLE_MARKER_END     14
#define FRAME_NUM 1
#define TOTAL_FRAMES 6
#define TOTAL_SLOTS 16
#define TOTAL_MEM 17
#define CURRENT_FPS     18
#define CYCLE_LO 19
#define CYCLE_HI 20
#define SEQ_ACT     21
#define SEQ_CUR     22
#define CHAIN_FADE      23
#define FRAME_DUP   24
#define MACRO       25
#define SUBRENDER   26
#define FADE_METHOD 27
#define FADE_ENTRY 28
#define FADE_ALPHA 29
#define SAMPLE_LOOP_STAT    30
#define SAMPLE_LOOP_STAT_STOP   31
#define SAMPLE_INV_COUNT    36
#define FEEDBACK 35
#define GLOBAL_CHAIN 37
#define MESSAGE_FORWARDING 38
#define AUDIO_BEAT_ENABLED      39
#define AUDIO_BEAT_OPEN         40
#define AUDIO_BEAT_LEVEL        41
#define AUDIO_BEAT_TRANSIENT    42
#define AUDIO_BEAT_HITS         43

#define AUDIO_BEAT_ENVELOPE     44
#define AUDIO_BEAT_FLUX         45
#define AUDIO_BEAT_BASS         46
#define AUDIO_BEAT_MID          47
#define AUDIO_BEAT_HIGH         48
#define AUDIO_BEAT_PULSE        49
#define AUDIO_BEAT_GATE         50
#define AUDIO_BEAT_BPM_X10      51
#define AUDIO_BEAT_AGE_MS       52
#define AUDIO_BEAT_SAMPLE_RATE  53
#define AUDIO_BEAT_HIT_SEQ      54
#define AUDIO_MUTED             55
#define RECORD_AUDIO_SOURCE     56
#define AUDIO_BEAT_ACTION       57

#define AUDIO_BEAT_CONFIG_FIRST           STATUS_SEQUENCE_END
#define AUDIO_BEAT_FREEZE_MS              (AUDIO_BEAT_CONFIG_FIRST + 0)
#define AUDIO_BEAT_COOLDOWN_MS            (AUDIO_BEAT_CONFIG_FIRST + 1)
#define AUDIO_BEAT_THRESHOLD_CFG          (AUDIO_BEAT_CONFIG_FIRST + 2)
#define AUDIO_BEAT_CHANNELS_CFG           (AUDIO_BEAT_CONFIG_FIRST + 3)
#define AUDIO_BEAT_PULSE_MS               (AUDIO_BEAT_CONFIG_FIRST + 4)
#define AUDIO_BEAT_GATE_MS                (AUDIO_BEAT_CONFIG_FIRST + 5)
#define AUDIO_BEAT_AUTO_MODE_CFG          (AUDIO_BEAT_CONFIG_FIRST + 6)
#define AUDIO_BEAT_AUTO_AMOUNT_CFG        (AUDIO_BEAT_CONFIG_FIRST + 7)
#define AUDIO_BEAT_SCRATCH_SENSITIVITY    (AUDIO_BEAT_CONFIG_FIRST + 8)
#define AUDIO_BEAT_SOURCE_LOSS_PAUSE      (AUDIO_BEAT_CONFIG_FIRST + 9)
#define AUDIO_BEAT_MONITOR_LATENCY        (AUDIO_BEAT_CONFIG_FIRST + 10)
#define AUDIO_BEAT_EFFECTIVE_LATENCY      (AUDIO_BEAT_CONFIG_FIRST + 11)
#define AUDIO_BEAT_CONFIG_LAST            (AUDIO_BEAT_CONFIG_FIRST + 12)
#define SAMPLE_AUDIO_VOLUME               VJ_STATUS_SAMPLE_AUDIO_VOLUME
#define AUDIO_MIX_MODE                    VJ_STATUS_AUDIO_MIX_MODE
#define AUDIO_MIX_CROSSFADE               VJ_STATUS_AUDIO_MIX_CROSSFADE
#define AUDIO_MIXER_STATUS_LAST           VJ_STATUS_AUDIO_MIXER_LAST

#define STREAM_BUFFER_ENABLED             VJ_STATUS_STREAM_BUFFER_ENABLED
#define STREAM_BUFFER_CAPACITY            VJ_STATUS_STREAM_BUFFER_CAPACITY
#define STREAM_BUFFER_FILLED              VJ_STATUS_STREAM_BUFFER_FILLED
#define STREAM_BUFFER_POSITION            VJ_STATUS_STREAM_BUFFER_POSITION
#define STREAM_BUFFER_SPEED               VJ_STATUS_STREAM_BUFFER_SPEED
#define STREAM_BUFFER_DIRECTION           VJ_STATUS_STREAM_BUFFER_DIRECTION
#define STREAM_BUFFER_MODE                VJ_STATUS_STREAM_BUFFER_MODE
#define STREAM_BUFFER_STATE               VJ_STATUS_STREAM_BUFFER_STATE
#define STREAM_TRICKPLAY_STATUS_LAST      VJ_STATUS_STREAM_TRICKPLAY_LAST

#ifndef SAMPLE_AUDIO_SYNC_OFF
#define SAMPLE_AUDIO_SYNC_OFF 0
#endif
#ifndef SAMPLE_AUDIO_SYNC_QUEUE
#define SAMPLE_AUDIO_SYNC_QUEUE 1
#endif
#ifndef SAMPLE_AUDIO_SYNC_TRACK_ALIGN
#define SAMPLE_AUDIO_SYNC_TRACK_ALIGN 2
#endif
#ifndef SAMPLE_AUDIO_SYNC_LIVE_EXTERNAL
#define SAMPLE_AUDIO_SYNC_LIVE_EXTERNAL 3
#endif
#ifndef SAMPLE_AUDIO_SYNC_MONITOR
#define SAMPLE_AUDIO_SYNC_MONITOR 4
#endif
#ifndef SAMPLE_AUDIO_SYNC_MONITOR_TRICKPLAY
#define SAMPLE_AUDIO_SYNC_MONITOR_TRICKPLAY 5
#endif
#ifndef SAMPLE_AUDIO_SYNC_TEMPO_FOLLOW
#define SAMPLE_AUDIO_SYNC_TEMPO_FOLLOW 6
#endif
#ifndef SAMPLE_AUDIO_SYNC_TEMPO_BRIDGE
#define SAMPLE_AUDIO_SYNC_TEMPO_BRIDGE 7
#endif
#ifndef SAMPLE_AUDIO_SYNC_MODE_MAX
#define SAMPLE_AUDIO_SYNC_MODE_MAX SAMPLE_AUDIO_SYNC_TEMPO_BRIDGE
#endif
#ifndef SAMPLE_AUDIO_SYNC_PROFILE_MAX
#define SAMPLE_AUDIO_SYNC_PROFILE_MAX 4
#endif

#define SAMPLE_AUDIO_SYNC_SOURCE              VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE
#define SAMPLE_AUDIO_SYNC_PROFILE             VJ_STATUS_SAMPLE_AUDIO_SYNC_PROFILE
#define SAMPLE_AUDIO_SYNC_MODE                VJ_STATUS_SAMPLE_AUDIO_SYNC_MODE
#define SAMPLE_AUDIO_SYNC_VIDEO_ANCHOR        VJ_STATUS_SAMPLE_AUDIO_SYNC_VIDEO_ANCHOR
#define SAMPLE_AUDIO_SYNC_WAV_ANCHOR_MS       VJ_STATUS_SAMPLE_AUDIO_SYNC_WAV_ANCHOR_MS
#define SAMPLE_AUDIO_SYNC_LOCK_DELTA_FRAMES   VJ_STATUS_SAMPLE_AUDIO_SYNC_LOCK_DELTA_FRAMES
#define SAMPLE_AUDIO_SYNC_LOCK_CONFIDENCE     VJ_STATUS_SAMPLE_AUDIO_SYNC_LOCK_CONFIDENCE
#define SAMPLE_AUDIO_SYNC_WAV_LENGTH_MS       VJ_STATUS_SAMPLE_AUDIO_SYNC_WAV_LENGTH_MS
#define SAMPLE_AUDIO_SYNC_WAV_LOOP            VJ_STATUS_SAMPLE_AUDIO_SYNC_WAV_LOOP
#define SAMPLE_AUDIO_SYNC_STATUS_LAST         VJ_STATUS_SAMPLE_AUDIO_SYNC_LAST

#define STREAM_BUFFER_STATE_UNSUPPORTED   0
#define STREAM_BUFFER_STATE_OFF           1
#define STREAM_BUFFER_STATE_EMPTY         2
#define STREAM_BUFFER_STATE_LIVE          3
#define STREAM_BUFFER_STATE_PLAYING       4
#define STREAM_BUFFER_STATE_PAUSED        5

#define AUDIO_SYNC_ENABLED       58
#define AUDIO_SYNC_OPEN          59
#define AUDIO_SYNC_RUNNING       60
#define AUDIO_SYNC_MODE          61
#define AUDIO_SYNC_SOURCE        62
#define AUDIO_SYNC_CHANNELS      63
#define AUDIO_SYNC_SAMPLE_RATE   64
#define AUDIO_SYNC_LEVEL_PCT     65
#define AUDIO_SYNC_TRANSIENT_PCT 66
#define AUDIO_SYNC_BPM_X10       67
#define AUDIO_SYNC_PHASE_PCT     68
#define AUDIO_SYNC_CONFIDENCE    69
#define AUDIO_SYNC_BRIDGE_ACTIVE 70
#define AUDIO_SYNC_RATIO_X1000   71
#define AUDIO_SYNC_CORRECTION    72
#define AUDIO_SYNC_TARGET_MODE   73
#define AUDIO_SYNC_TARGET_BPM_X10 74
#define AUDIO_SYNC_TARGET_CONFIDENCE 75
#define AUDIO_SYNC_MAX_CORRECTION 76
#define AUDIO_SYNC_BRIDGE_STATE  77
#define AUDIO_SYNC_TRACK_ALIGN_LOCKED         78
#define AUDIO_SYNC_TRACK_ALIGN_OFFSET_MS      79
#define AUDIO_SYNC_TRACK_ALIGN_CONFIDENCE     80
#define AUDIO_SYNC_TRACK_ALIGN_CORRECTION_PPM 81
#define AUDIO_SYNC_TRACK_ALIGN_STATE          82

#define STATUS_CHAIN_ENTRY_FXID                 83
#define STATUS_CHAIN_ENTRY_ISVIDEO              84
#define STATUS_CHAIN_ENTRY_NUM_PARAMETERS       85
#define STATUS_CHAIN_ENTRY_KF_TYPE              86
#define STATUS_CHAIN_ENTRY_KF_STATUS            87
#define STATUS_CHAIN_ENTRY_TRANSITION_ENABLED   88
#define STATUS_CHAIN_ENTRY_TRANSITION_LOOP      89
#define STATUS_CHAIN_ENTRY_SOURCE               90
#define STATUS_CHAIN_ENTRY_CHANNEL              91
#define STATUS_CHAIN_ENTRY_VIDEO_ENABLED        92
#define STATUS_CHAIN_ENTRY_BEAT_FLAG            93
#define STATUS_CHAIN_ENTRY_SUBRENDER_ENTRY      94
#define STATUS_CHAIN_ENTRY_P0                   95
#define STATUS_CHAIN_ENTRY_P1                   96
#define STATUS_CHAIN_ENTRY_P2                   97
#define STATUS_CHAIN_ENTRY_P3                   98
#define STATUS_CHAIN_ENTRY_P4                   99
#define STATUS_CHAIN_ENTRY_P5                   100
#define STATUS_CHAIN_ENTRY_P6                   101
#define STATUS_CHAIN_ENTRY_P7                   102
#define STATUS_CHAIN_ENTRY_P8                   103
#define STATUS_CHAIN_ENTRY_P9                   104
#define STATUS_CHAIN_ENTRY_P10                  105
#define STATUS_CHAIN_ENTRY_P11                  106
#define STATUS_CHAIN_ENTRY_P12                  107
#define STATUS_CHAIN_ENTRY_P13                  108
#define STATUS_CHAIN_ENTRY_P14                  109
#define STATUS_CHAIN_ENTRY_P15                  110
#define STATUS_CHAIN_ENTRY_LAST                 111
#define STATUS_CHAIN_ENTRY_TOKENS \
    (STATUS_CHAIN_ENTRY_LAST - STATUS_CHAIN_ENTRY_FXID)

#define STATUS_SEQUENCE_ACTIVE_BANK       111
#define STATUS_SEQUENCE_REVISION          112
#define STATUS_SEQUENCE_SIZE              113
#define STATUS_SEQUENCE_BANK0_REVISION    114
#define STATUS_SEQUENCE_BANK1_REVISION    115
#define STATUS_SEQUENCE_BANK2_REVISION    116
#define STATUS_SEQUENCE_BANK3_REVISION    117
#define STATUS_SEQUENCE_RESERVED          118
#define STATUS_SEQUENCE_LAST              118
#define STATUS_SEQUENCE_END               119

#define STATUS_SEQUENCE_UPDATED           STATUS_SEQUENCE_REVISION

#define SAMPLE_TRANSITION_ACTIVE  32
#define SAMPLE_TRANSITION_LENGTH  33
#define SAMPLE_TRANSITION_SHAPE  34
#define CURRENT_ENTRY 15
#define MODE_PLAIN  2
#define MODE_SAMPLE 0
#define MODE_PATTERN    3
#define MODE_STREAM 1
#define STREAM_COL_R    5
#define STREAM_COL_G    6
#define STREAM_COL_B    7
#define STREAM_RECORDED  11
#define STREAM_DURATION  10
#define STREAM_RECORDING 9
#define MAX_UI_PARAMETERS  16
#define STREAM_AVF 12

#define __MAX_TRACKS 16
#define HISTORY_PLAYMODES 4

#endif
