Document: reloaded
Title: Debian reloaded Manual
Author: <insert document author here>
Abstract: This manual describes what reloaded is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/reloaded/reloaded.sgml.gz

Format: postscript
Files: /usr/share/doc/reloaded/reloaded.ps.gz

Format: text
Files: /usr/share/doc/reloaded/reloaded.text.gz

Format: HTML
Index: /usr/share/doc/reloaded/html/index.html
Files: /usr/share/doc/reloaded/html/*.html

  
