$unshare_tmpdir_template = '/dev/shm/vj-sbuild/tmp.sbuild.XXXXXXXXXX';
$extra_repository_keys = [
    '/dev/shm/debian-ports-archive-keyring.gpg'
];
if (defined $ENV{'SBUILD_QEMU_CPU'} && $ENV{'SBUILD_QEMU_CPU'} =~ /\A(?:7400|power7)\z/) {
    $build_environment = {
        'QEMU_CPU' => $ENV{'SBUILD_QEMU_CPU'}
    };
}
1;
