Document: veejay
Title: Debian veejay Manual
Author: <insert document author here>
Abstract: This manual describes what veejay is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/veejay/veejay.sgml.gz

Format: postscript
Files: /usr/share/doc/veejay/veejay.ps.gz

Format: text
Files: /usr/share/doc/veejay/veejay.text.gz

Format: HTML
Index: /usr/share/doc/veejay/html/index.html
Files: /usr/share/doc/veejay/html/*.html

  
