/*
* buildinfo.h
* Do not edit this file, it is auto-generated.
*/
#define BUILD_HOSTNAME "cc1161740-a"
#define BUILD_KERNEL "2.6.28-smp"
#define BUILD_MACHINE "i686"
#define BUILD_OS "Linux"
#define BUILD_DATE "2009-07-10 18:18:17 UTC"
