#!/bin/sh
HOST=`uname -n`
KERNEL=`uname -r`
MACHINE=`uname -m`
OS=`uname -s`
DATE=`date -u "+%Y-%m-%d %H:%M:%S"`
cat <<EOF >build.h
/*
* buildinfo.h
* Do not edit this file, it is auto-generated.
*/
#define BUILD_HOSTNAME "${HOST}"
#define BUILD_KERNEL "${KERNEL}"
#define BUILD_MACHINE "${MACHINE}"
#define BUILD_OS "${OS}"
#define BUILD_DATE "${DATE} UTC"
EOF
