/* veejay - Linux VeeJay
 * 	     (C) 2002-2008 Niels Elburg <nwelburg@gmail.com> 
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#ifndef VIMS_H
#define VIMS_H

enum {
	VIMS_BUNDLE_START	=	500,
	VIMS_BUNDLE_END		=	599,	
	VIMS_MAX		=	602,
};

enum {
	VIMS_FXLIST_INC					=	1,
	VIMS_FXLIST_DEC					=	2,
	VIMS_FXLIST_ADD					=	3,	
	VIMS_PRINT_INFO					=	4,
	VIMS_PREVIEW_BW					=	8,

	VIMS_VIEWPORT					=	9,		
	VIMS_FRONTBACK					=	6,
	VIMS_PROJECTION					=	7,
	VIMS_COMPOSITE					=	47,
	VIMS_BEZERK						=	324,
	VIMS_DEBUG_LEVEL				=	325,
	VIMS_RESIZE_SDL_SCREEN			=	326,
	
	VIMS_RENDER_DEPTH				=	48,

	VIMS_FEEDBACK					= 	49,
	VIMS_CLEAR_MACRO_BANK			=	31,
	VIMS_MACRO						=	33,
	VIMS_MACRO_SELECT				=	34,
    VIMS_DEL_MACRO              	=	36,
	VIMS_PUT_MACRO		    		=	32,

	VIMS_SET_VOLUME					=	300,
	VIMS_FULLSCREEN					=	301,
	VIMS_SUSPEND					=	554,
	VIMS_QUIT						=	600,
	VIMS_CLOSE						=	601,


	VIMS_RECORD_DATAFORMAT			=	302,
	VIMS_SET_PLAIN_MODE				= 	303,
	VIMS_RECORD_AUDIO_SOURCE        =   304,

	VIMS_SWITCH_SAMPLE_STREAM		=	305,
	VIMS_AUDIO_ENABLE				=	306,
	VIMS_AUDIO_DISABLE				=	307,
	VIMS_AUDIO_TOGGLE_MUTE			=	313,
	VIMS_AUDIO_BEAT_TOGGLE			=	310,
	VIMS_AUDIO_BEAT_STATUS			=	311,
	VIMS_AUDIO_BEAT_CONFIG			=	314,
	VIMS_AUDIO_BEAT_FREEZE			=	317,
	VIMS_AUDIO_BEAT_COOLDOWN		=	318,
	VIMS_AUDIO_BEAT_THRESHOLD		=	331,
	VIMS_AUDIO_BEAT_CHANNELS		=	332,
	VIMS_AUDIO_BEAT_PRINT			=	333,
    VIMS_AUDIO_BEAT_ACTION          =   253,
    VIMS_AUDIO_BEAT_PULSE           =   254,
    VIMS_AUDIO_BEAT_GATE            =   255,
    VIMS_AUDIO_BEAT_AUTO_MODE       =   256,
    VIMS_AUDIO_BEAT_AUTO_AMOUNT     =   257,
    VIMS_AUDIO_BEAT_AUTO_RESET      =   258,
    VIMS_AUDIO_BEAT_STATE           =   259,
    VIMS_AUDIO_BEAT_UI_CONFIG       =   260,

	VIMS_AUDIO_SYNC_STATUS         =   261,
	VIMS_AUDIO_SYNC_MODE           =   262,
	VIMS_AUDIO_SYNC_JACK           =   263,
	VIMS_AUDIO_SYNC_WAV            =   264,
	VIMS_AUDIO_SYNC_TARGET         =   265,
	VIMS_AUDIO_SYNC_CORRECTION     =   266,
	VIMS_AUDIO_SYNC_PRINT          =   267,
    VIMS_AUDIO_BEAT_SCRATCH_SENSITIVITY = 268,
    VIMS_AUDIO_BEAT_SOURCE_LOSS_PAUSE   = 269,
    VIMS_AUDIO_BEAT_MONITOR_LATENCY     = 270,
    VIMS_AUDIO_MIX_MODE                  = 271,
    VIMS_AUDIO_MIX_CROSSFADE             = 272,
	VIMS_AUDIO_SYNC_WAV_PROFILE_SET      = 273,
	VIMS_AUDIO_SYNC_WAV_PROFILE_CLEAR    = 274,
	VIMS_SAMPLE_AUDIO_SYNC_SET           = 275,
	VIMS_SAMPLE_AUDIO_SYNC_CLEAR         = 276,
	VIMS_SAMPLE_AUDIO_SYNC_REARM         = 277,

	VIMS_SELECT_BANK				=	308,
	VIMS_SELECT_ID					=	309,

	VIMS_SAMPLE_RAND_START			=	315,
	VIMS_SAMPLE_RAND_STOP			=	316,
	VIMS_REC_AUTO_START				=	320,	
	VIMS_REC_STOP					=	321,
	VIMS_REC_START					=	322,
	VIMS_EFFECT_SET_BG				=	339,
	VIMS_SAMPLE_MODE				=	323,

	VIMS_SET_PLAY_MODE				=	327,
	VIMS_SET_MODE_AND_GO			=	328,
	VIMS_RGB_PARAMETER_TYPE			=	329,
	VIMS_SCREENSHOT					=	330,
	VIMS_SYNC_CORRECTION			=	334,
	VIMS_FRAMERATE					=	335,
    VIMS_SUB_RENDER_ENTRY           =   319,
	VIMS_SUB_RENDER					=	336,
	VIMS_ALPHA_COMPOSITE			=	337,
	VIMS_RESUME_ID					=	338,
	VIMS_VIDEO_PLAY_FORWARD			=	10,
	VIMS_VIDEO_PLAY_BACKWARD		=	11,
	VIMS_VIDEO_PLAY_STOP			=	12,
	VIMS_VIDEO_SKIP_FRAME			=	13,
	VIMS_VIDEO_PREV_FRAME			=	14,
	VIMS_VIDEO_SKIP_SECOND			=	15,
	VIMS_VIDEO_PREV_SECOND			=	16,
	VIMS_VIDEO_GOTO_START			=	17,
	VIMS_VIDEO_GOTO_END				=	18,
	VIMS_VIDEO_SET_FRAME			=	19,
	VIMS_VIDEO_SET_SPEED			=	20,
	VIMS_VIDEO_SET_SLOW				=	21,
	VIMS_VIDEO_MCAST_START			=	22,
	VIMS_VIDEO_MCAST_STOP			=	23,
	VIMS_VIDEO_SET_SPEEDK			=	24,		
	VIMS_VIDEO_PLAY_STOP_ALL		=	26,
    VIMS_VIDEO_SET_FRAME_PERCENTAGE =   27,
	VIMS_VIDEO_SET_FREEZE			=   30,
	VIMS_EDITLIST_PASTE_AT			=	50,
	VIMS_SPLIT_CONNECT_SHM			=	60,
	VIMS_SHM_WRITER					= 	25,
    VIMS_TOGGLE_TRANSITIONS         =   28, 
	VIMS_OUTPUT_Y4M_START			=	40,
	VIMS_OUTPUT_Y4M_STOP			=	41,
	VIMS_VLOOPBACK_START			=	45,
	VIMS_VLOOPBACK_STOP				=	46,
	VIMS_EDITLIST_COPY				=	51,
	VIMS_EDITLIST_DEL				=	52,
	VIMS_EDITLIST_CROP				=	53,
	VIMS_EDITLIST_CUT				=	54,
	VIMS_EDITLIST_ADD				=	55,
	VIMS_EDITLIST_ADD_SAMPLE		=	56,
	VIMS_EDITLIST_SAVE				=	58,
	VIMS_EDITLIST_LOAD				=	59,
	VIMS_MESSAGE_FORWARDING			=	70,

	VIMS_BUNDLE						=	80,
	VIMS_BUNDLE_DEL					=	81,
	VIMS_BUNDLE_ADD					=	82,
	VIMS_BUNDLE_ATTACH_KEY			=	83,
	VIMS_BUNDLE_FILE				=	84,
	VIMS_BUNDLE_SAVE				=	85,
	VIMS_BUNDLE_CAPTURE				=	86,
	VIMS_OSL						=	87,
	VIMS_OSD_EXTRA					=	88,
	VIMS_COPYRIGHT					=	89,
	VIMS_OSD						=	91,
	VIMS_COLOR_VIBRANCE   			=   92,

	VIMS_SAMPLE_NEW					=	100,
	VIMS_SAMPLE_SELECT				=	101,
	VIMS_SAMPLE_DEL					=	120,
	VIMS_SAMPLE_SET_LOOPTYPE		=	102,
	VIMS_SAMPLE_SET_DESCRIPTION		=	103,
	VIMS_SAMPLE_SET_SPEED			=	104,
	VIMS_SAMPLE_SET_START			=	105,
	VIMS_SAMPLE_SET_END				=	106,
	VIMS_SAMPLE_SET_DUP				=	107,
	VIMS_SAMPLE_SET_MARKER_START	=	108,
	VIMS_SAMPLE_SET_MARKER_END		= 	109,
	VIMS_SAMPLE_SET_MARKER			=	110,
	VIMS_SAMPLE_SKIP_FRAME			=	114,
	VIMS_SAMPLE_MOVE_MARKER			=   115,
	VIMS_SAMPLE_GROW_MARKER			=   116,
	VIMS_SAMPLE_SHRINK_MARKER		=   117,
	VIMS_SAMPLE_SET_VOLUME		=   118,
	VIMS_SAMPLE_CLEAR_MARKER		=	111,
	VIMS_SAMPLE_SYNC_SAMPLELIST     =   122,
	VIMS_SAMPLE_LOAD_SAMPLELIST_B64        =   123,
	VIMS_SAMPLE_LOAD_SAMPLELIST		=	125,
	VIMS_SAMPLE_SAVE_SAMPLELIST		=	126,
	VIMS_SAMPLE_DEL_ALL				=	121,
	VIMS_SAMPLE_COPY				=	127,
	VIMS_SAMPLE_SET_POSITION		=	128,
	VIMS_SAMPLE_REC_START			=	130,
	VIMS_SAMPLE_REC_STOP			=	131,
	VIMS_SAMPLE_CHAIN_ENABLE		=	112,
	VIMS_SAMPLE_CHAIN_DISABLE		=	113,
	VIMS_SAMPLE_KF_STATUS_PARAM		=	142,
	VIMS_SAMPLE_UPDATE				=	143,
	VIMS_SAMPLE_TOGGLE_LOOP			=	144,
	VIMS_SAMPLE_TOGGLE_RAND_LOOP	=	154,
	VIMS_SAMPLE_KF_STATUS			=	145,
	VIMS_SAMPLE_KF_RESET			=	147,
	VIMS_SAMPLE_HOLD_FRAME			=	148,
	VIMS_SAMPLE_NEXT				=	149,
	VIMS_SET_SAMPLE_START			=	150,
	VIMS_SET_SAMPLE_END				=	151,
	VIMS_SAMPLE_KF_CLEAR			=   152,
	VIMS_SAMPLE_MIX_SET_SPEED		=	153,
	VIMS_SAMPLE_MIX_TRANSITION		=	155,
	VIMS_SAMPLE_MIX_SET_DUP			=	156,
    VIMS_SAMPLE_SET_LOOPS           =   157,
	
	VIMS_PROJ_INC					=	160,
	VIMS_PROJ_DEC					=	161,
	VIMS_PROJ_SET_POINT				=	162,
	VIMS_PROJ_STACK					=	164,
	VIMS_PROJ_TOGGLE				=	165,

	VIMS_STREAM_COLOR				=	202,
	VIMS_STREAM_SELECT				=	201,
	VIMS_STREAM_ACTIVATE			=	205,
	VIMS_STREAM_DEACTIVATE			=	206,	
	VIMS_STREAM_CHAIN_ENABLE		=	212,
	VIMS_STREAM_CHAIN_DISABLE		=	213,
	VIMS_STREAM_SET_DESCRIPTION		=	203,
	VIMS_STREAM_SET_BRIGHTNESS		=	207,
	VIMS_STREAM_SET_CONTRAST		=	208,
	VIMS_STREAM_SET_HUE				=	209,
	VIMS_STREAM_SET_COLOR			=	210,
	VIMS_STREAM_SET_WHITE			=	211,
	VIMS_STREAM_SET_SATURATION		=	215,	
	VIMS_STREAM_SET_LENGTH			=	216,
	VIMS_STREAM_SET_V4LCTRL			=	217,	
	VIMS_STREAM_SET_ARG				=	219,
	VIMS_STREAM_SET_BUFFER_LENGTH	=	221,
	VIMS_STREAM_BUFFER_FORWARD		=	222,
	VIMS_STREAM_BUFFER_BACKWARD		=	223,
	VIMS_STREAM_BUFFER_STOP			=	224,
	VIMS_STREAM_BUFFER_SET_SPEED	=	225,
	VIMS_STREAM_BUFFER_SET_SLOW		=	226,
	VIMS_STREAM_BUFFER_SET_FRAME	=	227,

	VIMS_STREAM_OFFLINE_REC_START	=	228,
	VIMS_STREAM_OFFLINE_REC_STOP	=	229,
	VIMS_STREAM_REC_START			=	230,
	VIMS_STREAM_REC_STOP			=	231,
	VIMS_STREAM_BUFFER_SKIP_FRAME	=	232,
	VIMS_STREAM_BUFFER_SKIP_SECOND	=	233,
	VIMS_STREAM_BUFFER_PREV_SECOND	=	234,
	VIMS_STREAM_DELETE				=	220,
	VIMS_STREAM_NEW_AVFORMAT		=	239,
	VIMS_STREAM_NEW_V4L				=	240,
	VIMS_STREAM_NEW_DV1394			=	241,
	VIMS_STREAM_NEW_COLOR			=	242,
	VIMS_STREAM_NEW_Y4M				=	243,
	VIMS_STREAM_NEW_CALI			=	244,
	VIMS_V4L_BLACKFRAME				=	248,
	VIMS_V4L_CALI					=	249,
	VIMS_STREAM_NEW_UNICAST			=	245,
	VIMS_STREAM_NEW_MCAST			=	246,
	VIMS_STREAM_NEW_PICTURE			=	247,
	VIMS_STREAM_NEW_GENERATOR		=	250,
	VIMS_STREAM_NEW_SHARED			=	251,
	VIMS_STREAM_NEW_CLONE			=	252,

	VIMS_SEQUENCE_STATUS			=	340,
	VIMS_SEQUENCE_ADD				=	341,
	VIMS_SEQUENCE_DEL				=	342,

	VIMS_GLOBAL_CHAIN				=   343,
	VIMS_GLOBAL_CHAIN_COPY			=   344,
	VIMS_SEQUENCE_SELECT			=	345,
	VIMS_SEQUENCE_COPY				=	346,
	VIMS_SEQUENCE_CLEAR_ALL		=	347,

    VIMS_SET_TRANSITION             =   348,
	VIMS_CHAIN_ENTRY_SET_NARG_VAL	=	349,
	VIMS_CHAIN_ENTRY_CHANNEL_INC	=	350,
	VIMS_CHAIN_ENTRY_CHANNEL_DEC	=	351,
	VIMS_CHAIN_TOGGLE_ALL			=	352,
	VIMS_CHAIN_ENABLE				=	353,
	VIMS_CHAIN_DISABLE				=	354,
	VIMS_CHAIN_CLEAR				=	355,
	VIMS_CHAIN_FADE_IN				=	356,
	VIMS_CHAIN_FADE_OUT				=	357,
	VIMS_CHAIN_SET_ENTRY			=	359,
	VIMS_CHAIN_ENTRY_SET_EFFECT		=	360,
	VIMS_CHAIN_ENTRY_SET_PRESET		=	361,
	VIMS_CHAIN_ENTRY_SET_ARG_VAL	=	362,
	VIMS_CHAIN_ENTRY_SET_VIDEO_ON	=	363,
	VIMS_CHAIN_ENTRY_SET_VIDEO_OFF	=	364,
	VIMS_CHAIN_ENTRY_SET_DEFAULTS	=	365,
	VIMS_CHAIN_ENTRY_SET_CHANNEL	=	366,
	VIMS_CHAIN_ENTRY_SET_SOURCE		=	367,
	VIMS_CHAIN_ENTRY_SET_SOURCE_CHANNEL=368,
	VIMS_CHAIN_ENTRY_CLEAR			=	369,
	VIMS_CHAIN_MANUAL_FADE			=	370,
	VIMS_CHAIN_ENTRY_DOWN			=	371,
	VIMS_CHAIN_ENTRY_UP				=	372,
	VIMS_CHAIN_ENTRY_SOURCE_TOGGLE	=	373,
	VIMS_CHAIN_ENTRY_INC_ARG		=	374,
	VIMS_CHAIN_ENTRY_DEC_ARG		=	375,
	VIMS_CHAIN_TOGGLE				=	376,
	VIMS_CHAIN_ENTRY_SET_STATE		=	377,
	VIMS_ENTRY_CHANNEL_UP			=	378,
	VIMS_ENTRY_CHANNEL_DOWN			=	379,
	VIMS_CHAIN_ENTRY_BEAT_PARAM	=	380,
	VIMS_ENTRY_SOURCE_TOGGLE		=	381,
	VIMS_CHAIN_FOLLOW_FADE			=	382,
	VIMS_CHAIN_FADE_ENTRY			=	383,
	VIMS_CHAIN_FADE_METHOD			=	384,
	VIMS_CHAIN_FADE_ALPHA			=	385,
	VIMS_CHAIN_ENTRY_BEAT_TOGGLE	=	386,
	VIMS_CHAIN_FADE_KF_STATUS	=	387,
	VIMS_CHAIN_FADE_KF_CLEAR	=	388,
	VIMS_CHAIN_FADE_KF_AUDIO	=	389,
	VIMS_CHAIN_ENTRY_SWAP 		=   358,

	VIMS_FONT_POS					=	390,
	VIMS_FONT_COL					=	391,
	VIMS_FONT_SIZE_FONT				=	392,
	VIMS_SRT_ADD					=	393,
	VIMS_SRT_DEL					=	394,
	VIMS_SRT_UPDATE				=	395,
	VIMS_SRT_SAVE					=	396,
	VIMS_SRT_LOAD					=	397,
	VIMS_SRT_SELECT				=	398,


	VIMS_VIDEO_INFORMATION			=	400,
	VIMS_PROMOTION					=	444,
	VIMS_EFFECT_LIST				=	401,
	VIMS_EDITLIST_LIST				=	402,
	VIMS_BUNDLE_LIST				=	403,
	VIMS_STREAM_LIST				=	405,
	VIMS_STREAM_DEVICES				=	406,
	VIMS_SAMPLE_HISTORY_LIST		=	407,
	VIMS_SAMPLE_LIST				=	408,
	VIMS_STREAM_GET_V4L				=	409,
	VIMS_CHAIN_GET_ENTRY			=	410,
	VIMS_VIMS_LIST					=	411,
	VIMS_SAMPLE_INFO				=	413,
	VIMS_SAMPLE_OPTIONS				=	414,
	VIMS_DEVICE_LIST				=	415,
	VIMS_FONT_LIST					=	416,
	VIMS_SRT_LIST					=	417,
	VIMS_SRT_INFO					=	418,
	VIMS_SEQUENCE_LIST				=	419,
	VIMS_KEYLIST					=	420,
	VIMS_WORKINGDIR				=	421,
	VIMS_SAMPLE_STACK				=	422,
	VIMS_GET_IMAGE					=	423,
	VIMS_GET_SHM_EXT				=	424,
	VIMS_GET_SHM					=  	425,
	VIMS_GET_SPLIT_IMAGE			=	426,
	VIMS_GET_SAMPLE_IMAGE			=	427,
	VIMS_GET_STREAM_ARGS			=	428,
	VIMS_RGB24_IMAGE				=   433,
	VIMS_CALI_IMAGE					=	432,
	VIMS_CHAIN_GET_PARAMETERS		=	435,
	VIMS_GET_GENERATORS				=	436,
	VIMS_GET_FEEDBACK				=	437,
    VIMS_GET_MACRO              	=	438,
	VIMS_GET_ALL_MACRO				=	439,
	VIMS_CHAIN_LIST					=	448,
	VIMS_SEQUENCE_LIST_ALL			=	449,
	VIMS_SEQUENCE_QUEUE			=	451,
	VIMS_SEQUENCE_TIMELINE		=	452,
	VIMS_SEQUENCE_PATTERN_GET	=	453,
	VIMS_SEQUENCE_PATTERN_SET	=	278,
	VIMS_SEQUENCE_PATTERN_CLEAR	=	279,
	VIMS_TRACK_LIST				=	445,
	VIMS_SAMPLE_KF_GET				=	446,
	VIMS_PROJ_GET_POINT				=	447,
	VIMS_GET_FRAME					=	442,
	VIMS_GET_SAMPLELIST_BLOB				=	443,
	VIMS_GET_SAMPLELIST				= 450
};

#define VIMS_CHAIN_LIST_ENTRY_FORMAT "%02d%03d%1d%1d%1d%1d%03d%1d%1d"
#define VIMS_CHAIN_LIST_ENTRY_LENGTH (2+3+1+1+1+1+3+1+1)
#define VIMS_CHAIN_LIST_ENTRY_VALUES 9

#define VJ_SEQUENCE_PATTERN_FORMAT_MAX 32
#define VJ_SEQUENCE_PATTERN_DATA_MAX   (1024 * 1024)

/* Timeline body: bank(2), revision(10), finite(1), total(12), entries(3). */
/* Entry body: slot(3), source_id(5), source_type(2), start(12), length(12). */
#define VJ_SEQUENCE_TIMELINE_REPLY_PREFIX_LENGTH 8
#define VJ_SEQUENCE_TIMELINE_HEADER_LENGTH       28
#define VJ_SEQUENCE_TIMELINE_ENTRY_LENGTH        34

/* Pattern body: revision(10), format_length(3), data_length(8), format, Base64 data. */
#define VJ_SEQUENCE_PATTERN_REPLY_PREFIX_LENGTH  8
#define VJ_SEQUENCE_PATTERN_HEADER_LENGTH        21

enum {
    VJ_PLAYBACK_MODE_PLAIN = 2,
    VJ_PLAYBACK_MODE_SAMPLE = 0,
    VJ_PLAYBACK_MODE_PATTERN = 3,
    VJ_PLAYBACK_MODE_TAG = 1,
    VJ_PLAYBACK_MODE_MEM = 4,
};

enum {
    VJ_MAX_V4L_DEVICES = 2,
    VJ_MAX_IN_STREAMS = 4,
    VJ_MAX_OUT_STREAMS = 1,
    VJ_MAX_VLOOPBACK_PIPES = 8,
};

#define MAX_SEQUENCES		120
#define VJ_SEQUENCE_BANKS	4
#define MAX_SPEED		32
#define SAMPLE_MAX_EFFECTS 	20
#define PATTERN_MAX_TRACKS	3
#define CELL_LENGTH		30
#define ROW_SIZE		(PATTERN_MAX_TRACKS * CELL_LENGTH)
#define PATTERN_DEFAULT_LENGTH  (25*60)
#define EDIT_CUT		101
#define EDIT_PASTE_AT		102
#define EDIT_COPY		103
#define EDIT_CROP		104
#define EDIT_DEL		105
#define EL_MIN_BUF		(65535 * 4)
#define XMLTAG_BUNDLE_FILE  "ACTIONFILE"
#define XMLTAG_EVENT_AS_KEY "BUNDLE"
#define SOCKETFRAMELEN	(1024*4096)
#define VEEJAY_PORT_CMD 0
#define VEEJAY_PORT_STA 1
#define VEEJAY_PORT_DAT 3
#define VEEJAY_PORT_MAT 2
#define VEEJAY_PORT_OSC 6

#define VJ_STATUS_BASE_TOKENS              39
#define VJ_AUDIO_BEAT_STATUS_TOKENS        19
#define VJ_AUDIO_SYNC_STATUS_TOKENS        25
#define VJ_STATUS_CHAIN_ENTRY_FIXED_TOKENS 12
#define VJ_STATUS_CHAIN_ENTRY_PARAMETERS   16

#define VJ_AUDIO_STATUS_TOKENS \
    (VJ_AUDIO_BEAT_STATUS_TOKENS + VJ_AUDIO_SYNC_STATUS_TOKENS)

#define VJ_CHAIN_ENTRY_STATUS_TOKENS \
    (VJ_STATUS_CHAIN_ENTRY_FIXED_TOKENS + VJ_STATUS_CHAIN_ENTRY_PARAMETERS)

#define VJ_STATUS_CHAIN_ENTRY_TOKENS VJ_CHAIN_ENTRY_STATUS_TOKENS
#define VJ_SEQUENCE_STATUS_TOKENS         8
#define VJ_AUDIO_BEAT_CONFIG_STATUS_TOKENS 12
#define VJ_AUDIO_MIXER_STATUS_TOKENS      3
#define VJ_STREAM_TRICKPLAY_STATUS_TOKENS 8
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_TOKENS 9
#define VJ_ALPHA_STATUS_TOKENS             2

#define VJ_STATUS_EXPECTED_TOKENS \
    (VJ_STATUS_BASE_TOKENS + VJ_AUDIO_STATUS_TOKENS + VJ_CHAIN_ENTRY_STATUS_TOKENS + VJ_SEQUENCE_STATUS_TOKENS + VJ_AUDIO_BEAT_CONFIG_STATUS_TOKENS + VJ_AUDIO_MIXER_STATUS_TOKENS + VJ_STREAM_TRICKPLAY_STATUS_TOKENS + VJ_STATUS_SAMPLE_AUDIO_SYNC_TOKENS + VJ_ALPHA_STATUS_TOKENS)

#define VIMS_STATUS_TOKENS VJ_STATUS_EXPECTED_TOKENS
#define VJ_STATUS_ARRAY_SIZE (VIMS_STATUS_TOKENS + 1)

#define VJ_STATUS_CHAIN_ENTRY_FXID               83
#define VJ_STATUS_CHAIN_ENTRY_ISVIDEO            84
#define VJ_STATUS_CHAIN_ENTRY_NUM_PARAMETERS     85
#define VJ_STATUS_CHAIN_ENTRY_KF_TYPE            86
#define VJ_STATUS_CHAIN_ENTRY_KF_STATUS          87
#define VJ_STATUS_CHAIN_ENTRY_TRANSITION_ENABLED 88
#define VJ_STATUS_CHAIN_ENTRY_BEAT_PARAM_MASK   89
#define VJ_STATUS_CHAIN_ENTRY_TRANSITION_LOOP    VJ_STATUS_CHAIN_ENTRY_BEAT_PARAM_MASK
#define VJ_STATUS_CHAIN_ENTRY_SOURCE             90
#define VJ_STATUS_CHAIN_ENTRY_CHANNEL            91
#define VJ_STATUS_CHAIN_ENTRY_VIDEO_ENABLED      92
#define VJ_STATUS_CHAIN_ENTRY_BEAT_FLAG          93
#define VJ_STATUS_CHAIN_ENTRY_SUBRENDER_ENTRY    94
#define VJ_STATUS_CHAIN_ENTRY_P0                 95
#define VJ_STATUS_CHAIN_ENTRY_P1                 96
#define VJ_STATUS_CHAIN_ENTRY_P2                 97
#define VJ_STATUS_CHAIN_ENTRY_P3                 98
#define VJ_STATUS_CHAIN_ENTRY_P4                 99
#define VJ_STATUS_CHAIN_ENTRY_P5                 100
#define VJ_STATUS_CHAIN_ENTRY_P6                 101
#define VJ_STATUS_CHAIN_ENTRY_P7                 102
#define VJ_STATUS_CHAIN_ENTRY_P8                 103
#define VJ_STATUS_CHAIN_ENTRY_P9                 104
#define VJ_STATUS_CHAIN_ENTRY_P10                105
#define VJ_STATUS_CHAIN_ENTRY_P11                106
#define VJ_STATUS_CHAIN_ENTRY_P12                107
#define VJ_STATUS_CHAIN_ENTRY_P13                108
#define VJ_STATUS_CHAIN_ENTRY_P14                109
#define VJ_STATUS_CHAIN_ENTRY_P15                110
#define VJ_STATUS_CHAIN_ENTRY_LAST               111

#define VJ_STATUS_SEQUENCE_ACTIVE_BANK           111
#define VJ_STATUS_SEQUENCE_REVISION              112
#define VJ_STATUS_SEQUENCE_SIZE                  113
#define VJ_STATUS_SEQUENCE_BANK0_REVISION        114
#define VJ_STATUS_SEQUENCE_BANK1_REVISION        115
#define VJ_STATUS_SEQUENCE_BANK2_REVISION        116
#define VJ_STATUS_SEQUENCE_BANK3_REVISION        117
#define VJ_STATUS_SEQUENCE_STATE                 118
#define VJ_STATUS_SEQUENCE_SELECTED_MASK         VJ_STATUS_SEQUENCE_STATE
#define VJ_STATUS_SEQUENCE_RESERVED              VJ_STATUS_SEQUENCE_STATE
#define VJ_STATUS_SEQUENCE_LAST                  118
#define VJ_STATUS_SEQUENCE_END                   119
#define VJ_STATUS_SEQUENCE_UPDATED               VJ_STATUS_SEQUENCE_REVISION

#define VJ_SEQUENCE_STATUS_SELECTED_MASK_BITS    0x0f
#define VJ_SEQUENCE_STATUS_QUEUED_BANK_SHIFT     8
#define VJ_SEQUENCE_STATUS_QUEUED_BANK_BITS      0x0f
#define VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH_SHIFT 12
#define VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH_BITS  0x7ffff
#define VJ_SEQUENCE_STATUS_CONTROL_BITS          0x0fff
#define VJ_SEQUENCE_STATUS_PACK(mask, bank) \
    (((mask) & VJ_SEQUENCE_STATUS_SELECTED_MASK_BITS) | \
     ((((bank) >= 0 ? (bank) + 1 : 0) & VJ_SEQUENCE_STATUS_QUEUED_BANK_BITS) << VJ_SEQUENCE_STATUS_QUEUED_BANK_SHIFT))
#define VJ_SEQUENCE_STATUS_PACK_TRANSPORT(mask, bank, epoch) \
    (VJ_SEQUENCE_STATUS_PACK((mask), (bank)) | \
     (((epoch) & VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH_BITS) << VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH_SHIFT))
#define VJ_SEQUENCE_STATUS_SELECTED_MASK(value) \
    ((value) & VJ_SEQUENCE_STATUS_SELECTED_MASK_BITS)
#define VJ_SEQUENCE_STATUS_QUEUED_BANK(value) \
    ((((value) >> VJ_SEQUENCE_STATUS_QUEUED_BANK_SHIFT) & VJ_SEQUENCE_STATUS_QUEUED_BANK_BITS) - 1)
#define VJ_SEQUENCE_STATUS_CONTROL(value) \
    ((value) & VJ_SEQUENCE_STATUS_CONTROL_BITS)
#define VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH(value) \
    (((value) >> VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH_SHIFT) & VJ_SEQUENCE_STATUS_TRANSPORT_EPOCH_BITS)

#define VJ_STATUS_AUDIO_BEAT_FREEZE_MS           119
#define VJ_STATUS_AUDIO_BEAT_COOLDOWN_MS         120
#define VJ_STATUS_AUDIO_BEAT_THRESHOLD           121
#define VJ_STATUS_AUDIO_BEAT_CHANNELS            122
#define VJ_STATUS_AUDIO_BEAT_PULSE_MS            123
#define VJ_STATUS_AUDIO_BEAT_GATE_MS             124
#define VJ_STATUS_AUDIO_BEAT_AUTO_MODE           125
#define VJ_STATUS_AUDIO_BEAT_AUTO_AMOUNT         126
#define VJ_STATUS_AUDIO_BEAT_SCRATCH_SENSITIVITY 127
#define VJ_STATUS_AUDIO_BEAT_SOURCE_LOSS_PAUSE   128
#define VJ_STATUS_AUDIO_BEAT_MONITOR_LATENCY     129
#define VJ_STATUS_AUDIO_BEAT_EFFECTIVE_LATENCY   130
#define VJ_STATUS_AUDIO_BEAT_CONFIG_LAST         131

#define VJ_STATUS_SAMPLE_AUDIO_VOLUME            131
#define VJ_STATUS_AUDIO_MIX_MODE                 132
#define VJ_STATUS_AUDIO_MIX_CROSSFADE            133
#define VJ_STATUS_AUDIO_MIXER_LAST               134

#define VJ_STATUS_STREAM_BUFFER_ENABLED          VJ_STATUS_AUDIO_MIXER_LAST
#define VJ_STATUS_STREAM_BUFFER_CAPACITY         (VJ_STATUS_STREAM_BUFFER_ENABLED + 1)
#define VJ_STATUS_STREAM_BUFFER_FILLED           (VJ_STATUS_STREAM_BUFFER_ENABLED + 2)
#define VJ_STATUS_STREAM_BUFFER_POSITION         (VJ_STATUS_STREAM_BUFFER_ENABLED + 3)
#define VJ_STATUS_STREAM_BUFFER_SPEED            (VJ_STATUS_STREAM_BUFFER_ENABLED + 4)
#define VJ_STATUS_STREAM_BUFFER_DIRECTION        (VJ_STATUS_STREAM_BUFFER_ENABLED + 5)
#define VJ_STATUS_STREAM_BUFFER_MODE             (VJ_STATUS_STREAM_BUFFER_ENABLED + 6)
#define VJ_STATUS_STREAM_BUFFER_STATE            (VJ_STATUS_STREAM_BUFFER_ENABLED + 7)
#define VJ_STATUS_STREAM_TRICKPLAY_LAST          (VJ_STATUS_STREAM_BUFFER_ENABLED + 8)

#define VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE        VJ_STATUS_STREAM_TRICKPLAY_LAST
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_PROFILE       (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 1)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_MODE          (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 2)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_VIDEO_ANCHOR  (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 3)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_WAV_ANCHOR_MS (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 4)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_LOCK_DELTA_FRAMES (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 5)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_LOCK_CONFIDENCE   (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 6)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_WAV_LENGTH_MS (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 7)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_WAV_LOOP      (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 8)
#define VJ_STATUS_SAMPLE_AUDIO_SYNC_LAST          (VJ_STATUS_SAMPLE_AUDIO_SYNC_SOURCE + 9)

#define VJ_STATUS_ALPHA_INITIALIZE                VJ_STATUS_SAMPLE_AUDIO_SYNC_LAST
#define VJ_STATUS_ALPHA_VALUE                     (VJ_STATUS_ALPHA_INITIALIZE + 1)
#define VJ_STATUS_ALPHA_LAST                      (VJ_STATUS_ALPHA_INITIALIZE + 2)

#if VIMS_STATUS_TOKENS != 153
#error "VIMS_STATUS_TOKENS must be 153 for status fields 0..152"
#endif

#define VJ_INT_FIELD_MAX             12
#define VJ_STATUS_PREFIX_MAX         8
#define VJ_STATUS_WIRE_HEADER_LEN    6
#define VJ_STATUS_WIRE_MAX_PAYLOAD   9999

#define VJ_STATUS_REQUIRED_BUF_SIZE \
    (VJ_STATUS_PREFIX_MAX + (VIMS_STATUS_TOKENS * VJ_INT_FIELD_MAX) + 1)

#define VJ_STATUS_BUF_SIZE VJ_STATUS_REQUIRED_BUF_SIZE

#define MAX_EDIT_LIST_FILES 64
#define MAX_SPEED_AV    16

#define VJ_RECORD_AUDIO_SOURCE_AUTO 0
#define VJ_RECORD_AUDIO_SOURCE_ORIGINAL 1
#define VJ_RECORD_AUDIO_SOURCE_BEAT_JACK 2
#define VJ_RECORD_AUDIO_SOURCE_EXTERNAL VJ_RECORD_AUDIO_SOURCE_BEAT_JACK
#define VJ_RECORD_AUDIO_SOURCE_SILENCE 3

#define VJ_AUDIO_SYNC_MODE_OFF           0
#define VJ_AUDIO_SYNC_MODE_LIVE_EXTERNAL 1
#define VJ_AUDIO_SYNC_MODE_TEMPO_BRIDGE  2
#define VJ_AUDIO_SYNC_MODE_TRACK_ALIGN   3
#define VJ_AUDIO_SYNC_MODE_MONITOR       4
#define VJ_AUDIO_SYNC_MODE_TEMPO_FOLLOW  5
#define VJ_AUDIO_SYNC_MODE_MONITOR_TRICKPLAY 6
#define VJ_AUDIO_SYNC_MODE_MAX VJ_AUDIO_SYNC_MODE_MONITOR_TRICKPLAY


#define VJ_AUDIO_SYNC_SOURCE_NONE 0
#define VJ_AUDIO_SYNC_SOURCE_JACK 1
#define VJ_AUDIO_SYNC_SOURCE_WAV_FILE 2
#define VJ_AUDIO_SYNC_SOURCE_PUSH 3

#ifndef SAMPLE_AUDIO_SYNC_SOURCE_ORIGINAL
#define SAMPLE_AUDIO_SYNC_SOURCE_ORIGINAL VJ_AUDIO_SYNC_SOURCE_NONE
#endif
#ifndef SAMPLE_AUDIO_SYNC_SOURCE_JACK
#define SAMPLE_AUDIO_SYNC_SOURCE_JACK VJ_AUDIO_SYNC_SOURCE_JACK
#endif
#ifndef SAMPLE_AUDIO_SYNC_SOURCE_WAV
#define SAMPLE_AUDIO_SYNC_SOURCE_WAV VJ_AUDIO_SYNC_SOURCE_WAV_FILE
#endif
#ifndef SAMPLE_AUDIO_SYNC_SOURCE_SILENCE
#define SAMPLE_AUDIO_SYNC_SOURCE_SILENCE VJ_RECORD_AUDIO_SOURCE_SILENCE
#endif

#define VJ_AUDIO_SYNC_TARGET_MANUAL       0
#define VJ_AUDIO_SYNC_TARGET_CURRENT_CLIP 1

#define VJ_AUDIO_SYNC_BRIDGE_STATE_IDLE         0
#define VJ_AUDIO_SYNC_BRIDGE_STATE_WAIT_SOURCE  1
#define VJ_AUDIO_SYNC_BRIDGE_STATE_WAIT_TARGET  2
#define VJ_AUDIO_SYNC_BRIDGE_STATE_LOCKED       3
#define VJ_AUDIO_SYNC_BRIDGE_STATE_HOLD         4
#define VJ_AUDIO_SYNC_BRIDGE_STATE_FALLBACK     5

#define VJ_AUDIO_SYNC_TRACK_STATE_IDLE          0
#define VJ_AUDIO_SYNC_TRACK_STATE_WAIT_SOURCE   1
#define VJ_AUDIO_SYNC_TRACK_STATE_WAIT_TARGET   2
#define VJ_AUDIO_SYNC_TRACK_STATE_SEARCHING     3
#define VJ_AUDIO_SYNC_TRACK_STATE_LOCKED        4
#define VJ_AUDIO_SYNC_TRACK_STATE_HOLD          5
#define VJ_AUDIO_SYNC_TRACK_STATE_FALLBACK      6

#define VJ_KF_ENTRY_CHAIN_FADE 0
#define VJ_KF_PARAM_CHAIN_OPACITY 99

#endif
