.TH "yuv2rawdv" 1
.SH NAME
yuv2rawdv - encodes raw YCbCr (YUV 4:2:0) into a raw DV stream 
.SH SYNOPSIS
.B yuv2rawdv [options] 
.SH DESCRIPTION
.B yuv2rawdv
is a simple RAW DV encoder for raw YUV 4:2:0 frame streams. It
converts the YUV 4:2:0 to YUV 4:2:2 and encodes it using the Quasar
DV Codec

This program expects input from STDIN and writes a raw DV stream
to STDOUT.

.SH OPTIONS
The command line options allow to specify its behaviour
.TP
.B \-c [01]
Clamp luma (default 0=no) When enabled this will clamp the Luminance
channel to a range of 16-235. 
.TP
.B \-l [01]
Clamp chroma (default 0=no) When enabled this will clamp the Chrominance
channels to a range of 16-240
.TP
.B \-v [01]
Try to be silent or verbose
.SH USEFULL EXAMPLES
.TP
.B cat yuv4mpeg_file | yuv2rawdv | playdv
You can encode a yuv4mpeg stream from veejay through this program
and encode it to DV  while watching the resulting video with playdv
.TP
.B cat yuv4mpeg_file | yuv2rawdv > raw_dv_stream.dv
Encode a yuv4mpeg stream to raw dv format into a file
.SH BUGS
see BUGS in the source package
.SH AUTHOR
This man page was written by Niels Elburg.
If you have questions, remarks or you just want to
contact the developers, the main mailing list for this
project is: 
.I veejay-users@lists.sourceforge.net
For more info see the website at
.I http://veejay.sourceforge.net
.SH "SEE ALSO"
.B veejay yuv2rawdv rawdv2yuv sendVIMS  
